# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'


target 'smART_PMA' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for smART_PMA

  pod 'Firebase/Core'
  pod 'Firebase/Auth'



  target 'smART_PMATests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'smART_PMA-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for smART_PMA-tvOS

  target 'smART_PMA-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
